export let allData = {
  currentLanguage: 'en',
  currentUnitOfTemperature: 'celsius',
  coordinates: {
    lat: 0,
    lng: 0,
  },
  convertedCoordinates: {
    lat: '',
    lng: '',
  },
  temperatureToday: 0,
  temperatureTodayInFahrenheit: 0,
  temperatureNextThreeDays: [0, 0, 0],
  temperatureNextThreeDaysInFahrenheit: [0, 0, 0],
  weatherIcon: {
    today: '',
    nextThreeDays: [],
  },
  weather: '',
  feelsLike: 0,
  feelsLikeInFahrenheit: 0,
  humidity: 0,
  wind: 0,
  place: '',
  city: '',
  country: '',
  state: '',
  region: '',
  offset: 0,
  date: {
    year: 0,
    month: 0,
    day: 0,
    nextDays: [0, 0, 0],
    monthsOfNextDays: [0, 0, 0],
  },
  error: false,
};
