export let allData = {
  currentLanguage: 'en',
  currentUnitOfTemperature: 'celsius',
  coordinates: {
    lat: 0,
    lng: 0,
  },
  convertedCoordinates: {
    lat: '',
    lng: '',
  },
  temperatureToday: 0,
  temperatureTodayInFahrenheit: 0,
  temperatureNextThreeDays: [],
  temperatureNextThreeDaysInFahrenheit: [],
  weatherIcon: {
    today: '',
    nextThreeDays: [],
  },
  weather: '',
  feelsLike: '',
  feelsLikeInFahrenheit: '',
  humidity: '',
  wind: '',
  place: '',
  city: '',
  country: '',
  state: '',
  region: '',
  offset: 0,
  date: {
    year: 0,
    day: 0,
    nextDay: [0, 0, 0],
    nextDayMonth: [0, 0, 0],
  },
};
