export const LANGUAGE = {
  searchInput: {
    en: 'Search city or ZIP',
    ru: 'Поиск по городу или индексу',
    be: 'Пошук па горадзе ці індэксе',
  },
  searchButton: {
    en: 'Search',
    ru: 'Поиск',
    be: 'Пошук',
  },
  dayOfWeek: {
    en: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    ru: [
      'Воскресенье',
      'Понедельник',
      'Вторник',
      'Среда',
      'Четверг',
      'Пятница',
      'Суббота',
    ],
    be: [
      'Нядзеля',
      'Панядзелак',
      'Аўторак',
      'Серада',
      'Чацвер',
      'Пятніца',
      'Субота',
    ],
  },
  shortDayOfWeek: {
    en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    ru: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
    be: ['Нд', 'Пн', 'Аў', 'Ср', 'Чц', 'Пт', 'Сб'],
  },
  month: {
    en: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    ru: [
      'Января',
      'Февраля',
      'Марта',
      'Апреля',
      'Мая',
      'Июня',
      'Июля',
      'Августа',
      'Сентября',
      'Октября',
      'Ноября',
      'Декабря',
    ],
    be: [
      'Студзеня',
      'Лютага',
      'Сакавіка',
      'Красавіка',
      'Мая',
      'Чэрвеня',
      'Ліпеня',
      'Жнівеня',
      'Верасеня',
      'Кастрычніка',
      'Лістапада',
      'Снежня',
    ],
  },
  weatherConditions: {
    description: {
      en: '',
      ru: '',
      be: '',
    },
    feelsLike: {
      en: 'Feels like: ',
      ru: 'Ощущается как: ',
      be: 'Адчуваецца як: ',
    },
    wind: {
      en: 'Wind: ',
      ru: 'Ветер: ',
      be: 'Вецер: ',
    },
    windUnit: {
      en: 'm/s',
      ru: 'м/с',
      be: 'м/с',
    },
    humidity: {
      en: 'Humidity: ',
      ru: 'Влажность: ',
      be: 'Вільготнасць: ',
    },
  },
  latitude: {
    en: 'Latitude: ',
    ru: 'Широта: ',
    be: 'Шырата: ',
  },
  longitude: {
    en: 'Longitude: ',
    ru: 'Долгота: ',
    be: 'Даўгата: ',
  },
  error: {
    background: {
      en: 'Oops! Something went wrong.<br>You cannot update the background.',
      ru: 'Упс! Что-то пошло не так.<br>Вы не можете обновить фон.',
      be: 'Вох! Нешта пайшло не так.<br>Вы не можаце абнавіць фон.',
    },
    weather: {
      en: 'The weather data could not be obtained.<br>Please, try again later.',
      ru:
        'Не удалось получить данные о погоде.<br>Пожалуйста, попробуйте позже.',
      be: `Не атрымалася атрымаць дадзеныя пра надвор'е.<br>Калі ласка, паспрабуйце пазней.`,
    },
    currentCoordinates: {
      en: 'Unfortunately, your coordinates have not been received.',
      ru: 'К сожалению, ваши координаты не были получены.',
      be: 'На жаль, вашыя каардынаты не былі атрыманыя.',
    },
    query: {
      en: 'Request error. City not found.',
      ru: 'Ошибка запроса. Город не найден.',
      be: 'Памылка запыту. Горад не знойдзены.',
    },
  },
  preloader: {
    en: 'Loading...',
    ru: 'Загрузка...',
    be: 'Пачакайце...',
  },
};
